name: 💡 Proposal
description: Propose a change to docs.datenschmutz.dev
labels: [proposal, 'needs triage']
body:
  - type: markdown
    attributes:
      value: |
        Common reasons for proposals include:

        - Altering the infrastructure (e.g. swapping Webpack out with other bundlers);
        - Veränderung des Seiten aussehens
        - Hinzufügen einer Funktion. (z.B Suche)


        This is not for Doc / Cheat Sheet requests, please use the template "Documentation | Cheat Sheet Request" for that

        We give you maximum freedom to write an elaborated proposal illustrating why you think the change is beneficial for us, and what steps we should take to turn this into reality.

#  - type: checkboxes
#    attributes:
#      label: Have you read the Contributing Guidelines on issues?
#      options:
#        - label: I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).
#          required: true

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the proposal is.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Self-service
      description: |
        If you feel like you could contribute to this issue, please check the box below. This would tell us and other people looking for contributions that someone's working on it.
        If you do check this box, please send a pull request within 7 days after a maintainer's approval so we can still delegate this to someone else.
      options:
        - label: I'd be willing to do some initial work on this proposal myself.